phraseapp:
  access_token: 575340f3e69f1062be9326c581dc160cade0289c9d0b858c3b4b6a85d156bb73
  project_id: 537f5e1123508656dd1ab7d4ab83940e
  push:
    sources:
    - file: ./assets/lang/<locale_name>.json
      params:
        file_format: nested_json
  pull:
    targets:
    - file: ./assets/lang/<locale_name>.json
      params:
        file_format: nested_json
