phraseapp:
  access_token: cacfbc40f40de4f5f3949d16d2a620dc5590ce6d689d7e2167bd873b7653de4f
  project_id: 537f5e1123508656dd1ab7d4ab83940e
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        file_format: nested_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: nested_json
