phraseapp:
  access_token: d7eacb7eed6dbd196eb7e97c1e28297215ad4decd4e07ea5cb97da3a6482dbf9
  project_id: 537f5e1123508656dd1ab7d4ab83940e
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        file_format: react_simple_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: react_simple_json
