phraseapp:
  access_token: e002fcda210689b321792b8f6b778528dbdbbdd9fa39a947fbf4c0940f8707af
  project_id: 537f5e1123508656dd1ab7d4ab83940e
  file_format: react_simple_json
  pull:
    targets:
    - file: .\assets\lang\<locale_name>.json
      params: {locale_id: <locale_name>}
  push:
    sources:
    - file: .\assets\lang\<locale_name>.json
      params: {locale_id: <locale_name>}
