 
phraseapp:
  project_id: 537f5e1123508656dd1ab7d4ab83940e
  file_format: simple_json
  push:
    sources:
    - file: ./assets/lang/<locale_code>.json
      params:
        locale_id: <locale_code>
        file_format: simple_json
  pull:
    targets:
    - file: ./assets/lang/locales/<locale_code>.json
      params:
        file_format: simple_json
