phraseapp:
  access_token: 979032df19dd99cfdcb514db85b05653d564c6531e1386a1f88e85cec291b2da
  project_id: 537f5e1123508656dd1ab7d4ab83940e
  file_format: react_simple_json
  pull:
    targets:
    - file: ..\assets\lang\<locale_name>.json
      params: {locale_id: <locale_name>}
  push:
    sources:
    - file: ..\assets\lang\<locale_name>.json
